# Generated by Django 5.1 on 2024-08-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_actorold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActorOld',
        ),
    ]
